name: PitchBlack Recovery Project Builder Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Maintained by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space   # Easier
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Build PitchBlack Recovery
      uses: Niks-chan/pbrp-builder-action@main
      id: build
      with:
        MANIFEST_BRANCH: 'android-12.1'
        DEVICE_TREE: 'https://github.com/Niks-chan/pbrp_device_samsung_a51'
        DEVICE_TREE_BRANCH: 'pbrp'
        BUILD_TARGET: 'pbrp'
